[package]
name = "listener"
version = "0.1.0"
edition = "2024"

[dependencies]
model = { path = "../model" }
db = { path = "../db" }
bybit = { path = "../bybit" }
tinvest = { path = "../tinvest" }
tokio = { version = "1.48", features = ["full"] }
dotenv = "0.15.0"
log = "0.4"
simplelog = "0.12"
chrono = "0.4"